### ISSUE TITLE
on upgrading from rails 3.0.8 to 3.0.17 I am getting "undefined method `reputation_value_for' for #<User:...>"

### ISSUE THREAD

**Issue by jaygalligher** [twitter/activerecord-reputation-system#26]
Everything was running great in rails 3.0.8. I am upgrading to rails 3.2 eventually but to get things ready Ryan Bates in a Railscast recommended that I upgrade to rails 3.0.17 first. After upgrading to 3.0.17 I got "undefined method `reputation_value_for' for #<User: foo>". 

I am running rails in a rvm installed Ruby version 1.9.2. To be sure that it wasn't a problem with gems, I uninstalled 1.9.2 and reinstalled it. I installed the bundler gem and then ran bundle install. It still got the same error.

I then renamed the database migrations and ran rails g reputation_system. The old and new migration files were exactly the same.
